version: '3'

services:
  laravel:
    image: willianribeirodev/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    image: willianribeirodev/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8000:80"

networks:
  laranet:
    driver: bridge